[general]
live_config_reload = true
import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dynamic_padding = true

dimensions.columns = 140
dimensions.lines = 35

#decorations = "None"

opacity = 0.95
#blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 11

[keyboard]
bindings = [
  { key = "F11", mods = "None", action = "ToggleMaximized" },
  { key = "F12", action = "ToggleViMode" },
]
